export default {
  // Header component
  wishlist: 'Wishlist Now on Steam',
  comingSoon: 'Coming Late 2025',
  shareX: 'Share on X',
  shareFacebook: 'Share on Facebook',
  email: 'Email',
  copyLink: 'Copy Link',
  linkCopied: 'Link copied to clipboard!',
  tweetText: 'Wishlist Cosmic Run on Steam! Check it out:',
  emailSubject: 'Cosmic Run',
  emailBody: 'Wishlist Cosmic Run on Steam!',
  
  // Alt texts
  logo: 'Cosmic Run Logo',
  screenshot1: 'Screenshot 1',
  screenshot2: 'Screenshot 2',
  screenshot3: 'Screenshot 3',
  
  // Carousel
  prevSlide: 'Previous slide',
  nextSlide: 'Next slide',
  carouselCaptions: [
    "Swarms of alien ships attack as the player unleashes explosive abilities in a high-intensity run.",
    "Zogark's family members in front of the upgrade options for their spaceship.",
    "A look at the comic-inspired interface and colorful retro-futuristic UI elements.",
  ],
  
  // HeroShot
  heroAlt: 'Cosmic Run hero shot',
  heroTagline: 'Fast-paced, chaotic space roguelite with quirky humor and endless upgrades.',

  // GameInfo
  aboutGame: 'About the Game',
  gameDesc1: 'Cosmic Run is a fast-paced, single-player space roguelite filled with quirky humor, swarming enemies, and sheer endless ship upgrades. Outrun the galactic authorities with Zogark\'s rebellious family in a universe ruled by capitalism gone mad.',
  gameDesc2: 'Cosmic Run blends the chaotic flow of modern auto-battlers with deep customization and narrative flavor. Players control a self-built spaceship, upgrading parts like weapons, boosters, and defenses across action-packed short gameplay loops. Each run is unique thanks to procedural generation and permanent progression.',
  gameDesc3: 'Unlike many genre peers, Cosmic Run injects a narrative layer through dynamic dialogues that unfold during gameplay. Players choose between different family members of the rebellious Zogark clan, each offering distinct playstyles, dialogue, and backstory.',
  
  // StudioInfo
  aboutStudio: 'About Zinktank Labs',
  studioDesc: 'Zinktank Labs is a Hamburg-based indie game team founded by three friends who bonded over their shared love for chaotic, character-driven games. The team brings together over 30 years of combined experience in game development, system engineering, animation, and visual design. Cosmic Run represents their debut as a studio—fueled by a clear vision, a working MVP, and the goal to bring wild, weird, and accessible fun to the roguelite genre.',
  
  // Legal texts - Basic
  impressum: 'Impressum',
  privacyPolicy: 'Privacy Policy',
  cookieConsent: 'We use cookies to enhance your experience and analyze site traffic.',
  acceptCookies: 'Accept',
  rejectCookies: 'Reject',
  
  // Legal texts - Contact info
  contact: 'Contact',
  email: 'Email',
  phone: 'Phone',
  
  // Legal texts - Company info
  partners: 'Partners',
  registration: 'Registration',
  commercialRegister: 'Commercial Register',
  registrationNumber: 'Registration Number',
  vatId: 'VAT ID',
  taxNumber: 'Tax Number',
  
  // Legal texts - Privacy Policy sections
  privacyPolicyIntro: 'This Privacy Policy outlines how we collect, use, and protect your personal data when you visit our website.',
  dataCollection: 'Data Collection',
  dataCollectionIntro: 'We collect the following data:',
  dataCollectionVoluntary: 'Information you voluntarily provide (e.g., when contacting us)',
  dataCollectionAuto: 'Automatically collected data (IP address, browser type, device information)',
  dataCollectionCookies: 'Cookies and similar technologies',
  
  googleAnalytics: 'Google Analytics',
  googleAnalyticsIntro: 'This website uses Google Analytics to analyze website traffic. Google Analytics uses cookies to collect information about how visitors use our site. This information is transmitted to and stored by Google on servers in the United States.',
  googleAnalyticsAnonymization: 'We have activated IP anonymization, so your IP address is truncated before transmission to Google. Google uses this information to evaluate your use of the website, compile reports on website activity, and provide other services relating to website activity and internet usage.',
  googleAnalyticsOptOut: 'You can prevent the storage of cookies by adjusting your browser settings. You can also prevent the collection of data generated by the cookie by downloading and installing the browser plugin available at:',
  
  yourRights: 'Your Rights',
  yourRightsIntro: 'Under the GDPR, you have the right to:',
  rightAccess: 'Access your personal data',
  rightRectify: 'Rectify inaccurate personal data',
  rightDelete: 'Request the deletion of your personal data',
  rightObject: 'Object to the processing of your personal data',
  rightPortability: 'Data portability',
  rightWithdraw: 'Withdraw consent',
  
  privacyContact: 'If you have any questions about this Privacy Policy, please contact us at:'
}