<template>
  <div class="min-h-screen text-white font-mono px-6 py-8 max-w-3xl mx-auto relative">
    <!-- Star background with parallax effect -->
    <div 
      class="star-background fixed inset-0" 
      data-parallax 
      data-speed="-0.05"
      aria-hidden="true"
    ></div>
    
    <!-- Main content area with improved background for better readability -->
    <div class="content-container bg-gradient-to-b from-black to-gray-950 border border-gray-900 p-8 rounded-lg shadow-cosmic space-y-10 relative">
      <!-- Header with language toggle positioned to the right -->
      <header role="banner">
        <div class="flex justify-end mb-4">
          <h1 class="sr-only">Cosmic Run</h1>
          <LanguageToggle />
        </div>
      </header>
      
      <main id="main-content" role="main">
        <HeroShot />
        <CtaSection />
        <Share />
        <GameInfo />
        <Carousel />
        <StudioInfo />
      </main>
      
      <Footer ref="footerComponent" />
    </div>
    
    <!-- Cookie Consent Banner -->
    <CookieConsent
      :message="cookieMessage"
      :accept-button-text="t.acceptCookies || 'Accept'"
      :reject-button-text="t.rejectCookies || 'Reject'"
      :learn-more-text="t.privacyPolicy || 'Privacy Policy'"
      @show-privacy-policy="showPrivacyPolicy"
      @accept-cookies="handleCookieAccept"
      @reject-cookies="handleCookieReject"
    />
  </div>
  
  <!-- Privacy Policy Modal -->
  <div v-if="showPrivacyModal" class="fixed inset-0 bg-black/80 flex items-center justify-center z-[200] p-4" @click.self="showPrivacyModal = false">
    <div class="bg-zinc-900 border border-accent/50 p-6 rounded-lg max-w-2xl max-h-[80vh] overflow-y-auto">
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-xl text-accent font-bold">{{ t.privacyPolicy || 'Privacy Policy' }}</h2>
        <button @click="showPrivacyModal = false" class="text-gray-400 hover:text-white" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      
      <div class="text-left space-y-4">
        <p>This Privacy Policy outlines how Zinktank Labs GmbH ("we", "our" or "us") collects, uses, and protects your personal data when you visit our website.</p>
        
        <h4 class="text-accent">Data Collection</h4>
        <p>We collect the following data:</p>
        <ul class="list-disc pl-5">
          <li>Information you voluntarily provide (e.g., when contacting us)</li>
          <li>Automatically collected data (IP address, browser type, device information)</li>
          <li>Cookies and similar technologies</li>
        </ul>
        
        <h4 class="text-accent">Google Analytics</h4>
        <p>This website uses Google Analytics to analyze website traffic. Google Analytics uses cookies to collect information about how visitors use our site. This information is transmitted to and stored by Google on servers in the United States.</p>
        <p>We have activated IP anonymization, so your IP address is truncated before transmission to Google. Google uses this information to evaluate your use of the website, compile reports on website activity, and provide other services relating to website activity and internet usage.</p>
        <p>You can prevent the storage of cookies by adjusting your browser settings. You can also prevent the collection of data generated by the cookie by downloading and installing the browser plugin available at: <a href="https://tools.google.com/dlpage/gaoptout" class="text-accent underline">https://tools.google.com/dlpage/gaoptout</a></p>
        
        <h4 class="text-accent">Your Rights</h4>
        <p>Under the GDPR, you have the right to:</p>
        <ul class="list-disc pl-5">
          <li>Access your personal data</li>
          <li>Rectify inaccurate personal data</li>
          <li>Request the deletion of your personal data</li>
          <li>Object to the processing of your personal data</li>
          <li>Data portability</li>
          <li>Withdraw consent</li>
        </ul>
        
        <h4 class="text-accent">Contact</h4>
        <p>If you have any questions about this Privacy Policy, please contact us at:</p>
        <p>Zinktank Labs GmbH<br>Email: privacy@zinktanklabs.com</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, provide, computed, onMounted, defineAsyncComponent } from 'vue'
import translations from './i18n'
import { useParallax } from './composables/useParallax'
import { detectUserLanguage } from './i18n'
import appConfig from './config/appConfig'

// Import critical components immediately
import HeroShot from './components/HeroShot.vue'
import CtaSection from './components/CtaSection.vue'
import LanguageToggle from './components/LanguageToggle.vue'
import CookieConsent from './components/CookieConsent.vue'

// Lazy-load components that appear lower in the page
const Share = defineAsyncComponent(() => import('./components/Share.vue'))
const GameInfo = defineAsyncComponent(() => import('./components/GameInfo.vue'))
const Carousel = defineAsyncComponent(() => import('./components/Carousel.vue'))
const StudioInfo = defineAsyncComponent(() => import('./components/StudioInfo.vue'))
const Footer = defineAsyncComponent(() => import('./components/Footer.vue'))

// Initialize parallax effect for the star background
useParallax()

// Language handling with persistence
const lang = ref('en') // Default language

// State for privacy policy modal
const showPrivacyModal = ref(false)
const footerComponent = ref(null)

// Cookie consent message with language support
const cookieMessage = computed(() => {
  return t.value.cookieConsent || 'We use cookies to enhance your experience and analyze site traffic.'
})

// Function to set language and save to localStorage
const setLang = (newLang) => {
  if (newLang in translations) {
    lang.value = newLang
    localStorage.setItem('preferred-language', newLang)
    document.documentElement.setAttribute('lang', newLang)
  }
}

// Create a reactive translation object that updates when language changes
const t = computed(() => translations[lang.value] || translations.en)

// Function to show privacy policy modal
const showPrivacyPolicy = () => {
  showPrivacyModal.value = true
}

// Cookie consent handlers
const handleCookieAccept = () => {
  // Enable analytics
  if (window.gtag) {
    window.gtag('consent', 'update', {
      'analytics_storage': 'granted'
    })
  }
}

const handleCookieReject = () => {
  // Disable analytics
  if (window.gtag) {
    window.gtag('consent', 'update', {
      'analytics_storage': 'denied'
    })
  }
}

// Initialize language on component mount
onMounted(() => {
  // Try to get language from localStorage first
  const savedLang = localStorage.getItem('preferred-language')
  
  if (savedLang && savedLang in translations) {
    lang.value = savedLang
  } else {
    // If no saved preference, detect from browser
    const detectedLang = detectUserLanguage()
    lang.value = detectedLang
    localStorage.setItem('preferred-language', detectedLang)
  }
  
  // Set the lang attribute on the html element for accessibility
  document.documentElement.setAttribute('lang', lang.value)
  
  // Initialize Google Analytics with consent mode
  if (window.gtag) {
    const cookieConsent = localStorage.getItem('cookie-consent')
    window.gtag('consent', 'default', {
      'analytics_storage': cookieConsent === 'accepted' ? 'granted' : 'denied'
    })
  }
  
  // Apply theme colors from appConfig to CSS variables
  document.documentElement.style.setProperty('--accent-color', appConfig.theme.accentColor);
  document.documentElement.style.setProperty('--accent-color-rgb', appConfig.theme.accentColorRgb);
  document.documentElement.style.setProperty('--accent-color-darker', appConfig.theme.accentColorDarker);
})

// Provide reactive lang and setter to children
provide('lang', lang)
provide('setLang', setLang)
provide('t', t) // Provide translations
provide('showPrivacyPolicy', showPrivacyPolicy) // Provide privacy policy function
</script>

<style>
/* Star background styles */
.star-background {
  z-index: 0; /* Place above black background but behind content */
  background: #000 url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzAwMCIvPjxjaXJjbGUgY3g9IjEwIiBjeT0iMTAiIHI9IjEiIGZpbGw9IiNmZmYiIG9wYWNpdHk9IjAuMyIvPjxjaXJjbGUgY3g9IjMwIiBjeT0iMzAiIHI9IjAuNSIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC41Ii8+PGNpcmNsZSBjeD0iNDUiIGN5PSI1NSIgcj0iMSIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC43Ii8+PGNpcmNsZSBjeD0iNjAiIGN5PSIxNSIgcj0iMC43NSIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC40Ii8+PGNpcmNsZSBjeD0iOTAiIGN5PSI0MCIgcj0iMC40IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjYiLz48Y2lyY2xlIGN4PSIxMzAiIGN5PSI4MCIgcj0iMSIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC41Ii8+PGNpcmNsZSBjeD0iMTgwIiBjeT0iNjAiIHI9IjAuOCIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC43Ii8+PGNpcmNsZSBjeD0iMTcwIiBjeT0iMTUwIiByPSIwLjkiIGZpbGw9IiNmZmYiIG9wYWNpdHk9IjAuNCIvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjE4MCIgcj0iMC42IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjMiLz48Y2lyY2xlIGN4PSIxMDAiIGN5PSIxNzAiIHI9IjEiIGZpbGw9IiNmZmYiIG9wYWNpdHk9IjAuNSIvPjxjaXJjbGUgY3g9IjQwIiBjeT0iMTkwIiByPSIwLjciIGZpbGw9IiNmZmYiIG9wYWNpdHk9IjAuNCIvPjxjaXJjbGUgY3g9IjIwIiBjeT0iMTAwIiByPSIwLjUiIGZpbGw9IiNmZmYiIG9wYWNpdHk9IjAuNiIvPjxjaXJjbGUgY3g9IjExMCIgY3k9IjEyMCIgcj0iMC44IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjciLz48Y2lyY2xlIGN4PSIxOTAiIGN5PSIxMCIgcj0iMC42IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjMiLz48Y2lyY2xlIGN4PSI3MCIgY3k9IjgwIiByPSIxIiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjUiLz48Y2lyY2xlIGN4PSIxNDAiIGN5PSIzMCIgcj0iMC43IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjQiLz48Y2lyY2xlIGN4PSI2MCIgY3k9IjEyMCIgcj0iMC42IiBmaWxsPSIjZmZmIiBvcGFjaXR5PSIwLjQiLz48Y2lyY2xlIGN4PSIxNzAiIGN5PSIxMDAiIHI9IjAuNCIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC42Ii8+PGNpcmNsZSBjeD0iODAiIGN5PSIxNTAiIHI9IjAuOSIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC43Ii8+PGnpcmNsZSBjeD0iMTEwIiBjeT0iNjAiIHI9IjAuNyIgZmlsbD0iI2ZmZiIgb3BhY2l0eT0iMC41Ii8+PC9zdmc+') center/cover;
  animation: twinkling 100s linear infinite;
  pointer-events: none; /* Allow clicking through the background */
}

/* Fix for the gray bar at the bottom */
html, body {
  background-color: #000 !important; /* Force black background */
  margin: 0;
  padding: 0;
  overflow-x: hidden;
}

/* Add extra content to ensure scrolling area has stars */
.min-h-screen::after {
  content: "";
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  height: 100vh; /* This extends beyond the visible area */
  z-index: -2;
  background-color: #000; /* Black background */
}

/* Make the star background extend beyond the viewport */
.star-background {
  height: 200vh; /* 2x the viewport height */
}

/* Enhanced content container styling */
.content-container {
  backdrop-filter: blur(2px); /* Subtle blur effect */
  box-shadow: 0 0 40px rgba(0, 0, 0, 0.9), 
              0 0 15px rgba(var(--accent-color-rgb), 0.07), 
              0 0 5px rgba(var(--accent-color-rgb), 0.03);
  position: relative;
  z-index: 10; /* Ensure content is above the starry background */
  overflow: hidden; /* Keep everything contained */
  background-color: rgba(5, 5, 15, 0.95); /* Very dark background with high opacity */
  color: rgba(255, 255, 255, 0.95); /* Ensure high contrast for text */
}

/* Optional glow effect around the container */
.content-container::before {
  content: '';
  position: absolute;
  inset: -1px;
  background: linear-gradient(45deg, rgba(var(--accent-color-rgb), 0.03), transparent 30%, rgba(var(--accent-color-rgb), 0.03), transparent 70%, rgba(var(--accent-color-rgb), 0.03));
  z-index: -1;
  border-radius: inherit;
  pointer-events: none;
}

/* Custom shadow for cosmic theme */
.shadow-cosmic {
  box-shadow: 0 5px 20px rgba(0, 0, 0, 0.8), 
              0 0 10px rgba(var(--accent-color-rgb), 0.1);
}

/* Accessibility focus styles */
*:focus-visible {
  outline: 2px solid var(--accent-color) !important;
  outline-offset: 3px;
}

/* Ensure keyboard navigation is visible */
button:focus, a:focus, input:focus, select:focus {
  box-shadow: 0 0 0 3px rgba(var(--accent-color-rgb), 0.5);
}

/* Custom utility classes for color */
.text-accent {
  color: var(--accent-color);
}

.bg-accent {
  background-color: var(--accent-color);
}

.border-accent {
  border-color: var(--accent-color);
}

@keyframes twinkling {
  from {
    background-position: 0 0;
  }
  to {
    background-position: 1000px 1000px;
  }
}
</style>
